name: .NET CI/CD

env:
  PRERELEASE_BRANCHES: '' # Comma separated list of prerelease branch names. 'alpha,rc, ...'
  CASCADES: '' # Comma separated list of cascading repos. 'dolittle/DotNet.SDK,...'
  NUGET_OUTPUT: Artifacts/NuGet

on:
  push:
    branches:
    - '**'
  pull_request:
    types: [closed]

jobs:
  ci:
    name: Integration
    runs-on: ubuntu-latest
    outputs:
      should-publish: ${{ steps.context.outputs.should-publish }}
      current-version: ${{ steps.context.outputs.current-version }}
      release-type: ${{ steps.context.outputs.release-type }}
      cascading-release: ${{ steps.context.outputs.cascading-release }}

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - run: dotnet build
    - run: dotnet test
    - name: Establish context
      id: context
      uses: dolittle/establish-context-action@v2
      with:
        prerelease-branches: ${{ env.PRERELEASE_BRANCHES }}

  release:
    name: Deploy
    runs-on: ubuntu-latest
    needs: ci
    if: ${{ needs.ci.outputs.should-publish == 'true' }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
      - name: Increment version
        id: increment-version
        uses: dolittle/increment-version-action@v2
        with:
          version: ${{ needs.ci.outputs.current-version }}
          release-type: ${{ needs.ci.outputs.release-type }}
      - name: Create GitHub Release
        uses: dolittle/github-release-action@v1
        with:
          cascading-release: ${{ needs.ci.outputs.cascading-release }}
          version: ${{ steps.increment-version.outputs.next-version }}
      - name: Create packages
        run: dotnet pack --configuration Release -o ${{ env.NUGET_OUTPUT }} /p:PackageVersion=${{ steps.increment-version.outputs.version }} -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg
      - name: Push NuGet packages
        run: dotnet nuget push ${{ env.NUGET_OUTPUT }}/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
      - name: Cascade
        uses: dolittle/cascade-action@v1
        if: ${{ env.CASCADES != '' }}
        with:
          token: ${{ secrets.BUILD_PAT }}
          version: ${{ steps.increment-version.outputs-next-version }}
          cascades: ${{ env.CASCADES }}
